name: Publish package to GitHub Packages

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: [self-hosted]

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com"
          scope: "@bit-gpt"
      - name: Create .npmrc
        run: |
          cd ./typescript/package
          echo "engine-strict=true" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          echo "@bit-gpt:registry=https://npm.pkg.github.com" >> .npmrc
      - name: Build and publish
        run: |
          cd ./typescript/package
          npm ci
          npm run build
          npm publish
